# Generated by Django 4.2.7 on 2023-11-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churro_app', '0002_career_contact_menuitem_order_survey_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('eventType', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('additionalInfo', models.TextField()),
            ],
        ),
    ]
